import {Candy} from './Candy.js';
import {Chocolate} from './Chocolate.js';
import {GummyCandy} from './GummyCandy.js';
import {Marzipan} from './Marzipan.js';
import {Gift} from './Gift.js';
console.log(`New Year's gift composition is:`);
const gummyCandy1 = new GummyCandy("Tropical Gummy Bears", 80, 70, 2,  "Tropical", "Soft");
const gummyCandy2 = new GummyCandy("Sour Worms", 100, 75, 1, "Sour", "Chewy");
const marzipan1 = new Marzipan("Classic Marzipan", 50, 60, 2, 40);
const marzipan2 = new Marzipan("Almond Marzipan", 70, 65, 1, 50);
const chocolate = new Chocolate("Dark Chocolate", 180, 95, 1, 80);
const candy = new Candy("Milky country", 70, 60, 2, "Fruity");
const gift = new Gift("Ivan");
gift.addSweet(gummyCandy1);
gift.addSweet(gummyCandy2);
gift.addSweet(marzipan1);
gift.addSweet(marzipan2);
gift.addSweet(chocolate);
gift.addSweet(candy);
gift.listSweets();
console.log(`........................................................`);
console.log(`Total weight: ${gift.getTotalWeight()}g`);
console.log(`--------------------------------------------------------`);
gift.sortSweetsBy("sugarContent");
console.log("Sorted by sugar content:");
gift.listSweets();
console.log(`--------------------------------------------------------`);
const sweetsInRange = gift.findSweetsInRange("sugarContent", 65, 70);
console.log("Sweets with sugar content between 65% and 70%:");
sweetsInRange.forEach(sweet => {
  console.log(sweet.getSweetInfo());
});
